### PR TITLE
Fix incorrect error code for checking if security switches are needed

### PR DESCRIPTION
**Pull request by surprise**
Title, [this](https://mojang-api-docs.netlify.app/sq-flow/check-if-sqs-needed.html) has the wrong code for the error

### CODE REVIEW

**Comment by surprise** [comment]
[Source from one of my sniping programs](https://s.ehardy.co/rNaG), if someone else could test and comment if they get the same it would be much appreciated :)

**Comment by whatwhatwhatwhatwhatwhat** [comment]
Will test in a bit and I’ll let you know if it shows up the same.

**Comment by surprise** [comment]
> Also feel free to join MCB’s discord and ping me there if you want faster replies to future issues or pull requests
@whatwhatwhatwhatwhatwhat Is that MCBYT or something else? if so, what is your discord tag?

**Comment by whatwhatwhatwhatwhatwhat** [comment]
> > Also feel free to join MCB’s discord and ping me there if you want faster replies to future issues or pull requests
> 
> @whatwhatwhatwhatwhatwhat Is that MCBYT or something else? if so, what is your discord tag?

MCBYT. My Discord tag is what#1111 (private, used only for talking, no adding) and my alt is ahhhhhhhh#9468 (anyone can DM this I believe).

**Comment by whatwhatwhatwhatwhatwhat** [comment]
LGTM!

**Comment by whatwhatwhatwhatwhatwhat** [comment]
Oops, accidentally closed. Merged now. Thanks for your contribution. In the next update I'll add your credit.

**Pull request merged**
